### ISSUE TITLE
Proper naming convention for homepage

### ISSUE THREAD

**Issue by Pedestal19** [otuyamicah/Forms-tables#1]
Please which of the pages is your homepage? Homepage should be called index followed by the file extension.

**Comment by otuyamicah** [comment]
do you mean I should rename my homepage to "index.html"?

**Comment by Pedestal19** [comment]
Yeah, the first point of entry in a web app is the index.html

**Comment by otuyamicah** [comment]
have fixed all the issues!

**Comment by Pedestal19** [comment]
Okay, Would look at them

**Comment by Pedestal19** [comment]
Great Work! Nice!

So before doing this, you did not know that I told you to use fieldset?

Why are the issues still open?

Your commit for sorting them is supposed to close the issue.
